# Generated by Django 6.0.4 on 2026-04-26 18:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
